server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    discovery:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: company
      username: company
      password: password